//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KfFluentMvc.WinForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KfFluentMvc.WinForms.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding to the Checked propery requires that the current control be of type CheckBox.
        /// </summary>
        internal static string BindFromCheckedPropertyRequiresCheckBox {
            get {
                return ResourceManager.GetString("BindFromCheckedPropertyRequiresCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current component must be of type ToolStripItem.
        /// </summary>
        internal static string ComponentMustBeToolStripItem {
            get {
                return ResourceManager.GetString("ComponentMustBeToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create a model binding without first setting the component to bind to. Invoke the MvcBuilder&lt;M&gt;.WithComponent method before creating bindings.
        /// </summary>
        internal static string ComponentNotSet {
            get {
                return ResourceManager.GetString("ComponentNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current control must be of type TreeView.
        /// </summary>
        internal static string ControlMustBeTreeView {
            get {
                return ResourceManager.GetString("ControlMustBeTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create a model binding without first setting the control to bind to. Invoke the MvcBuilder&lt;M&gt;.WithControl method before creating bindings.
        /// </summary>
        internal static string ControlNotSet {
            get {
                return ResourceManager.GetString("ControlNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &quot;{0}&quot; not found in class &quot;{1}&quot;.
        /// </summary>
        internal static string EventNotFoundMessage {
            get {
                return ResourceManager.GetString("EventNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method signature. Can only bind a controller to a method with Action() or Func&lt;Task&gt; signature.
        /// </summary>
        internal static string InvalidBoundMethodSignatureMessage {
            get {
                return ResourceManager.GetString("InvalidBoundMethodSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; not found in class &quot;{1}&quot;.
        /// </summary>
        internal static string MethodNotFoundMessage {
            get {
                return ResourceManager.GetString("MethodNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model must implement IValidatingMvcModel.
        /// </summary>
        internal static string ModelMustBeIValidatingMvcModel {
            get {
                return ResourceManager.GetString("ModelMustBeIValidatingMvcModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MvcBuilder.CurrentControl type does not match the C1 type parameter.
        /// </summary>
        internal static string PrimaryControlIncorrectType {
            get {
                return ResourceManager.GetString("PrimaryControlIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; not found in class &quot;{1}&quot;.
        /// </summary>
        internal static string PropertyNotFoundMessage {
            get {
                return ResourceManager.GetString("PropertyNotFoundMessage", resourceCulture);
            }
        }
    }
}
